spring:
  application:
    name: api-gateway
 



server:
  port: 9001

Zuul:
 routes:
  user-services:
    path: /user-services/**
    service-id: user-service
  task-services:
    path: /task-services/**
    service-id: task-service
    
    
 eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   
    