spring:
  application:
    name: user-service
 
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password@123
    
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true 
      

server:
  port: 8082
  
#task-service:
  #ribbon:
    #listOfServers: http://localhost:8083/,http://localhost:8085/,http://localhost:8087/
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/